CFLAGS=-m64 -pedantic -pedantic-errors -std=gnu99 -Werror -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wno-error=maybe-uninitialized -O3

all: exo0

.PHONY: clean
clean:
	rm -f exo0
