#!/usr/bin/perl -w
# vim: syntax=perl

use strict;

# fwd declarations
sub from_rat;

# read inputs
# grep on length gets rid of zero-length fields
my @inputs = map { &from_rat($_); } grep(length, split(/[\s\[\]]+/, <STDIN>));
my $NDEEP = shift(@inputs);

my $current = $inputs[0];
for (my $i=0; $i < $NDEEP; $i++) {
    $current = $inputs[$current];
}

print STDOUT $current, "\n";
print STDERR "\n", $current, "\n";

##
## SUBROUTINES
##

# takes 2%1 and returns 2 - always an integer
sub from_rat {
    my $rat = shift(@_);
    my ($num, $den) = split(/%/,$rat);

    if (defined($den)) {
        return int($num / $den);
    } else {
        return int($num);
    }
}
